# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hillhacks
email: mail@hillhacks.in
description: > # this means to ignore newlines until "baseurl:"
  We invite people to share, demonstrate, teach and talk about the things they love. It doesn't have to be about technology, but from people that show passion in what they do. Free-thinkers, tinkerers and creative minds, artists, techies and hobbyists, hackers and makers, crafters and scientist, humanists and engineers, activists and coders, geeks and nerds, designers and philosophers, natural and artificial intelligences and other interesting beings doing interesting stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: hillhacks
github_username:  https://github.com/hillhacks

# Build settings
markdown: kramdown
